export interface StrokeBuilder {
    addPoint(x: number, y: number, width: number): void;
    clear(): void;
    computeGeometry(join: number, cap: number, soft: boolean): void;
    getVertices(): Float32Array;
    getIndices(): Uint32Array;
    getTexCoords(): Float32Array;
    getDirectionalities(): Float32Array;
    /** Must be called when done to free C++ memory. */
    delete(): void;
}

export interface JoinStyleEnum {
    None: number;
    Bevel: number;
    Miter: number;
    Round: number;
}

export interface CapStyleEnum {
    Flat: number;
    Square: number;
    Round: number;
}

export interface InputSmoother {
    /** Feed one raw pointer event. Smoothed output available via getSmoothedPoints(). */
    addPoint(x: number, y: number): void;
    /** Float32Array view: [x0,y0, x1,y1, ...] — valid until next addPoint() or reset(). */
    getSmoothedPoints(): Float32Array;
    /** Reset physics state. Call between strokes. */
    reset(): void;
    /** Must be called when done to free C++ memory. */
    delete(): void;
}

export interface StampInstance {
    /** Stamp centre position, canvas space. */
    x: number;
    y: number;
    radius: number;
    opacity: number;
    /** Rotation angle in degrees, clockwise from up. */
    angle: number;
    /** Aspect ratio [0..1]; 1.0 = circle. */
    squish: number;
}

export interface StampPlacer {
    /**
     * Feed one (smoothed) pointer position. Per-point overrides are optional;
     * pass undefined / omit to use the BrushParams defaults.
     * Stamps generated by this point are available via getStamps().
     */
    addPoint(
        x: number,
        y: number,
        radius?: number,
        opacity?: number,
        angle?: number,
        squish?: number,
    ): void;
    /**
     * Float32Array view — 6 floats per stamp: [x, y, radius, opacity, angle, squish, ...]
     * Valid until the next addPoint() or reset() call.
     */
    getStamps(): Float32Array;
    /** Number of stamps in the current getStamps() buffer. */
    getStampCount(): number;
    /** Reset placement state. Call between strokes. */
    reset(): void;
    /** Reset placement state. Call between strokes. */
    reset(
        radius: number,
        opacity: number,
        angle: number,
        squish: number,
        spacing: number,
        spacingBias: number,
        spacingJitter: number,
        opacityJitter: number,
        radiusJitter: number,
        rotationJitter: number,
        rotateToStroke: boolean,
    ): void;
    /** Must be called when done to free C++ memory. */
    delete(): void;
}

export interface StrokeBuilderConstructor {
    new (): StrokeBuilder;
}

export interface InputSmootherConstructor {
    /**
     * @param mass default 0.9
     * @param drag default 0.921
     * @param iterations default 6
     * @param smoothLevel default 2
     */
    new (mass: number, drag: number, iterations: number, smoothLevel: number): InputSmoother;
    /**
     * Constructor without parameters, uses default values.
     */
    new (): InputSmoother;
}

export interface StampPlacerConstructor {
    /**
     * @param radius         default 0.5 — base stamp radius (normalized, relative to canvas height)
     * @param opacity        default 1   — base stamp opacity [0..1]
     * @param angle          default 0   — base stamp angle in degrees
     * @param squish         default 1   — aspect ratio [0..1], 1 = circle
     * @param spacing        default 0   — if > 0, overrides proportional default (radius * 0.5 * spacingBias)
     * @param spacingBias    default 1   — multiplier on computed inter-stamp spacing
     * @param spacingJitter  default 0   — random spacing variation [0..1]
     * @param opacityJitter  default 0   — random opacity variation [0..1]
     * @param radiusJitter   default 0   — random radius variation [0..1]
     * @param rotationJitter default 0   — random angle per stamp (degrees)
     * @param rotateToStroke default false — align stamp to stroke direction
     */
    new (
        radius: number,
        opacity: number,
        angle: number,
        squish: number,
        spacing: number,
        spacingBias: number,
        spacingJitter: number,
        opacityJitter: number,
        radiusJitter: number,
        rotationJitter: number,
        rotateToStroke: boolean,
    ): StampPlacer;
    /**
     * Constructor without parameters, uses default values.
     */
    new (): StampPlacer;
}

export interface AnnotationPlatformModule {
    StrokeBuilder: StrokeBuilderConstructor;
    InputSmoother: InputSmootherConstructor;
    StampPlacer: StampPlacerConstructor;
    JoinStyle: JoinStyleEnum;
    CapStyle: CapStyleEnum;
}

declare function AnnotationPlatform(): Promise<AnnotationPlatformModule>;
export default AnnotationPlatform;
